# Generated by Django 2.1.8 on 2019-06-16 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huayuan', '0012_ardiunodata_personal_information_pipei'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ardiunoData',
        ),
    ]
