# Generated by Django 2.1.8 on 2019-06-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('huayuan', '0014_auto_20190617_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='ardiunoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Humidity', models.FloatField(default=0)),
                ('Temperature', models.FloatField(default=0)),
                ('Soil_1', models.FloatField(default=0)),
                ('Soil_2', models.FloatField(default=0)),
                ('Soil_3', models.FloatField(default=0)),
                ('Soil_4', models.FloatField(default=0)),
                ('Avg_soil', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='personal_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='小明', max_length=30)),
                ('usersex', models.CharField(default='男', max_length=4)),
                ('userNation', models.CharField(default='汉', max_length=50)),
                ('userbirthday', models.DateField(verbose_name='出生日期')),
                ('userage', models.IntegerField()),
                ('user_cai_type', models.CharField(default='黄豆', max_length=20)),
                ('userIdCard', models.CharField(max_length=18)),
                ('userFaith', models.CharField(max_length=20)),
                ('userRemarks', models.CharField(max_length=100)),
                ('userphone', models.CharField(max_length=11)),
                ('userAddress', models.CharField(max_length=200)),
                ('userImage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='pipei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testbox', models.CharField(max_length=3)),
                ('plant_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('useremail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
